sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: qZpQZ9RXB8d4utMadY3bdoTu7oo7u8aRUdq8QRzRsryW48L+xcCT6vrXXOp3zauNICmn/B+3gMMt1bPL+94uVc9/wI9an3q+e6tzazKLsuSqhW55Swg00YO4zah360kM+SEC1ZlR6cA+Dts/MNILvBUnfhIXhKBXb6KY6/jqGc26Yk5S2Suydku/rj/omee8CN8aLqA1+Tvb/jLAnMWG3nId9Jf3QHHwg58jRE3mmjdx0I1pJflyufUZ8uv3buZELlqy4IeGF5Qdgv5EK4XkNGBThEue6w+WeoCATy71iDO2ekP90zdRCnbyf9K8eVZzE0BQRsLbfDc3l/dnNN9EZTgWxmR2UIJ66tI4AtskoC/YyICFQzl7BzxZw71cYvkp1iLtIFWi3lE9qZ/mePcYROqrULg7qZFXQ/ZE3gV2Y0demzDHY6sbl3BEPShqUoC4fQMCoJrO5fLZbdF8b63ZWHpIIp/WdBZvzQjBuJNj4HJNOXR8DCpwv4ZT5ZtmO3Qt4hfRRbD/0rt6wt+7VosxR57yxHam+nuQxNWqyVNuwr8tzrglJtG45GDfW03OAqtijV7VS9/mD/Gk8qzjcUvowvTk/Mi62VT1Ry5opcBQtZaHd4uIUyO5yHyiZXg3UdEWSZXvwM8EEgcpOAVF6Tl9RY/0VnZnxP82a7+giiM4RfI=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: gw2L0javtvs4qHnKv5/kxyMAH/+vdgeMVC2/5Y7JAGrSFrvJE3g5PeraMSNXdoCtqVVg7U3a+W1VlnP1MZ8/OnOXz6XHQdhEEQVF1F9hNVM63B4+k9B+EmudtWaRGUa86AY/34viqHSOxvpdwejLYz48Vmbw3tiyxm8o4qMGGf5xh8ugRuM/Uk4dQn9n3qE2qFyVeWuRz3W/FN+AclMZHxGNW8V9qhVmVKopMmRj9/OGqBaZDV7mQzCvtFDVt6SNSitMfb6tCwQ5TnMySwyUUyxJZeZ53lu0Pb3ilbeZwivq+fVJq1Vcj7QcQU5KkFZkSzZYfZDUx+IOHliLb9X3z2QzvIZ8f9hadRAhY70LsNpTy2s60FKi4ZlVe2jGIhNJJxxr2nElxje3ecI2w5qcO4yW6E257RQKYEIWdBd37IX+n2EXiANajmcSf3USOVBYdRt7zK+nRT3yCMnUuG0FuFWucCas9FyWghP7kiURuIuWbln6FkMugWmw7DgSmA0rOa8ffus/I4+k/tOpN/SzTi8JJXOypf2rKfgPXsGu1vI4O1u94NfI3pxNV7OICTVCt30WCHxiX16Z3cF17vl3PYDHACZtirx1T+sOTzGWHfR3yhLty57cxjKi78NorO+28yzlO6UqrA+WmMQkGx2duAjPMr+qx9xR65+hSFMqVuw=
